Use Symbol (BROKEN, ref #2144): $$is_a_module => $$is_a_module_s
$ bundle exec rake mspec_ruby_nodejs

TypeError: Cannot read property '$new' of undefined
  from corelib/runtime.js:1873:7:in `Opal.defs'
  from corelib/helpers.rb:4:3:in `bridge'
  from corelib/helpers.rb:3:1:in `module'
  from corelib/runtime.js:2450:7:in `Opal.load'
  from corelib/runtime.js:2478:5:in `Opal.require'
  from opal/base.rb:2:1:in `require'
  from corelib/runtime.js:2450:7:in `Opal.load'
  from corelib/runtime.js:2478:5:in `Opal.require'
  from opal.rb:1:1:in `require'
  from /tmp/opal-system-runner-20210524-8479-1ggxlx9:25091:3:in `null'
rake aborted!